-- Starter and evolved cards for Fatal Exception
-- Includes id, tier, playEffect, destructorEffect, and ramCost

local CardTree = {
  -- Tier 0: Starter Cards
  -- Starter card definitions for Fatal Exception
-- Each card includes id, tier, name, cost, playEffect, and destructorEffect
  {
    id = 0,
    tier = 0,
    name = "Core Sync",
    cost = 1,
    playEffect = { type = "progress", amount = 1 },
    destructorEffect = { type = "progress", amount = -2 },
  },
  {
    id = 1,
    tier = 0,
    name = "Failsafe Trigger",
    cost = 1,
    playEffect = { type = "threat", amount = -1 },
    destructorEffect = { type = "threat", amount = 2 },
  },
  {
    id = 2,
    tier = 0,
    name = "Overcommit",
    cost = 1,
    playEffect = { type = "progress", amount = 1 },
    destructorEffect = { type = "threat", amount = 3 },
  },
  {
    id = 3,
    tier = 0,
    name = "Defensive Lag",
    cost = 1,
    playEffect = { type = "threat", amount = -2 },
    destructorEffect = { type = "progress", amount = -1 },
  },
  {
    id = 4,
    tier = 0,
    name = "System Shuffle",
    cost = 1,
    playEffect = { type = "shuffle_disruptor" },
    destructorEffect = { type = "draw_to_destructor", amount = 1 },
  },
  {
    id = 5,
    tier = 0,
    name = "Memory Probe",
    cost = 1,
    playEffect = { type = "draw", amount = 2 },
    destructorEffect = { type = "draw_to_destructor", amount = 1 },
  },
  {
    id = 6,
    tier = 0,
    name = "Jumpstart",
    cost = 2,
    playEffect = { type = "progress", amount = 2 },
    destructorEffect = { type = "progress", amount = -3 },
  },
  {
    id = 7,
    tier = 0,
    name = "Firewall Collapse",
    cost = 2,
    playEffect = { type = "threat", amount = -2 },
    destructorEffect = { type = "threat", amount = 3 },
  },
  {
    id = 8,
    tier = 0,
    name = "Anomaly Mask",
    cost = 2,
    playEffect = { type = "nullify_destructor", amount = 1 },
    destructorEffect = { type = "threat", amount = 3 },
  },
  {
    id = 9,
    tier = 0,
    name = "Pulse Spike",
    cost = 0,
    canPlay = false,
    onDiscard = { type = "ram_multiplier", amount = 2 },
    playEffect = { type = "none" },
    destructorEffect = { type = "threat_multiplier", amount = 2 },
  },

  -- Tier 1: First Evolutions
  {
    id = "guru_loop",
    tier = 1,
    playEffect = "+2 system_progress",
    destructorEffect = "+4 threat",
    ramCost = 2,
  },
  {
    id = "garbage_fragmentation",
    tier = 1,
    playEffect = "-3 threat",
    destructorEffect = "lose top card from deck",
    ramCost = 2,
  },
  {
    id = "memory_canary",
    tier = 1,
    playEffect = "peek 2 Destructor",
    destructorEffect = "+1 threat & shuffle",
    ramCost = 1,
  },
  {
    id = "heap_detonation",
    tier = 1,
    playEffect = "+3 system_progress",
    destructorEffect = "+5 threat",
    ramCost = 2,
  },
  {
    id = "backup_restore",
    tier = 1,
    playEffect = "+2 RAM",
    destructorEffect = "delete 1 progress on system",
    ramCost = 2,
  },
  {
    id = "kernel_oops",
    tier = 1,
    playEffect = "-2 threat",
    destructorEffect = "add random Tier 0 to Destructor",
    ramCost = 1,
  },
  {
    id = "pointer_sanitizer",
    tier = 1,
    playEffect = "+1 system_progress",
    destructorEffect = "nullify next Destructor card",
    ramCost = 2,
  },
  {
    id = "debug_trace",
    tier = 1,
    playEffect = "remove 2 Destructor",
    destructorEffect = "+3 threat",
    ramCost = 2,
  },
  {
    id = "adaptive_thrusters",
    tier = 1,
    playEffect = "draw 2, keep 1",
    destructorEffect = "discard 2 lowest cost cards",
    ramCost = 1,
  },
  {
    id = "overclock",
    tier = 1,
    playEffect = "full RAM restore",
    destructorEffect = "-2 RAM for 3 turns",
    ramCost = 3,
  },

  -- Tier 2: Second Evolutions
  {
    id = "recursive_boot",
    tier = 2,
    playEffect = "+4 system_progress",
    destructorEffect = "threat doubles this turn",
    ramCost = 3,
  },
  {
    id = "entropy_compactor",
    tier = 2,
    playEffect = "-4 threat",
    destructorEffect = "+1 Destructor draw next turn",
    ramCost = 3,
  },
  {
    id = "system_forecaster",
    tier = 2,
    playEffect = "reorder top 3 Destructor",
    destructorEffect = "+1 threat per reordered card",
    ramCost = 2,
  },
  {
    id = "memory_corruption_chain",
    tier = 2,
    playEffect = "+4 system_progress",
    destructorEffect = "add 2 random Tier 1s to Destructor",
    ramCost = 3,
  },
  {
    id = "parity_backup",
    tier = 2,
    playEffect = "+3 RAM",
    destructorEffect = "hand size reduced next turn",
    ramCost = 2,
  },
  {
    id = "exploit_chain",
    tier = 2,
    playEffect = "-3 threat, gain 1 RAM",
    destructorEffect = "shuffle all Oops into Destructor",
    ramCost = 3,
  },
  {
    id = "integrity_rewriter",
    tier = 2,
    playEffect = "remove 2 Destructor, +1 system_progress",
    destructorEffect = "+1 threat for each removed",
    ramCost = 3,
  },
  {
    id = "rollback_analysis",
    tier = 2,
    playEffect = "choose 1 of 3 past Destructor cards to remove",
    destructorEffect = "+4 threat",
    ramCost = 3,
  },
  {
    id = "predictive_execution",
    tier = 2,
    playEffect = "draw 3 if hand < 3",
    destructorEffect = "destroy lowest-cost card in deck",
    ramCost = 2,
  },
  {
    id = "quantum_reboot",
    tier = 2,
    playEffect = "reset all RAM & redraw",
    destructorEffect = "add top 2 cards to Destructor",
    ramCost = 3,
  },
}

return CardTree
